import type { Metadata } from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  // SignInButton,
  // SignUpButton,
  // SignedIn,
  // SignedOut,
  // UserButton,
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/sonner";

const font = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
}); 

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en">
        <body
          className={`${font.variable} antialiased`}>
          {children}
          <Toaster/>
        </body>
      </html> 
    </ClerkProvider>
  );
}
